name: FHP vMenu Server
version: 1.0.0
author: FHP Management System
description: Florida Highway Patrol vMenu server template with nat2k15 base styling

variables:
  serverName: "Florida Highway Patrol | Serious RP"
  maxPlayers: "32"

tasks:
  # Download Base Resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    dest: ./resources/[cfx-default]

  # Download vMenu
  - action: download_github
    src: https://github.com/TomGrobbe/vMenu
    dest: ./resources/[vMenu]
    ref: master

  # Create server.cfg
  - action: write_file
    file: ./server.cfg
    data: |
      sv_hostname "Florida Highway Patrol | Serious RP"
      sv_maxclients 32
      set sv_enforceGameBuild 2944
      sv_scriptHookAllowed 0
      sv_endpointPrivacy true
      set onesync on
      setr vmenu_use_permissions true
      setr vmenu_menu_staff_only false
      setr vmenu_enable_weather_sync true
      setr vmenu_enable_time_sync true
      setr vmenu_enable_dynamic_weather true
      setr vmenu_teleport_to_wp true
      setr vmenu_keep_spawned_vehicles_persistent false
      setr vmenu_disable_server_info_convars false
      setr vmenu_disable_daily_update_checks false
      exec resources.cfg
      exec permissions.cfg
      ensure vMenu
      ensure fhp_vehicles
      ensure fhp_liveries
      ensure fhp_dispatch

  # Create permissions.cfg
  - action: write_file
    file: ./permissions.cfg
    data: |
      add_principal group.admin group.moderator
      add_principal group.superadmin group.admin
      add_ace group.superadmin vmenu.everything allow
      add_ace group.superadmin command allow
      add_ace group.admin vmenu.everything allow
      add_ace group.moderator vmenu.player_options allow
      add_ace group.moderator vmenu.vehicle_options allow
      add_ace group.moderator vmenu.vehicle_spawner allow
      add_ace group.moderator vmenu.weather_options allow
      add_ace group.moderator vmenu.time_options allow
      add_ace group.trusted vmenu.player_options allow
      add_ace group.trusted vmenu.vehicle_options allow
      add_ace group.trusted vmenu.vehicle_spawner allow
      add_ace group.user vmenu.player_options allow
      add_ace group.user vmenu.vehicle_spawner.fhp allow

  # Create resources.cfg
  - action: write_file
    file: ./resources.cfg
    data: |
      ensure mapmanager
      ensure chat
      ensure spawnmanager
      ensure sessionmanager
      ensure basic-gamemode
      ensure hardcap
      ensure baseevents
      ensure vMenu
      ensure Luxart
      ensure fhp_vehicles
      ensure fhp_liveries
      ensure fhp_callouts
      ensure fhp_dispatch
      ensure fhp_mdt

  # Create fxmanifests for FHP resources
  - action: write_file
    file: ./resources/[fhp]/fhp_vehicles/fxmanifest.lua
    data: |
      fx_version 'cerulean'
      game 'gta5'
      author 'FHP'
      description 'FHP Vehicle Configuration'
      version '1.0.0'
      shared_script 'config.lua'

  - action: write_file
    file: ./resources/[fhp]/fhp_liveries/fxmanifest.lua
    data: |
      fx_version 'cerulean'
      game 'gta5'
      author 'FHP'
      description 'FHP Livery Configuration'
      version '1.0.0'

  - action: write_file
    file: ./resources/[fhp]/fhp_dispatch/fxmanifest.lua
    data: |
      fx_version 'cerulean'
      game 'gta5'
      author 'FHP'
      description 'FHP Dispatch Configuration'
      version '1.0.0'

  - action: write_file
    file: ./resources/[fhp]/fhp_callouts/fxmanifest.lua
    data: |
      fx_version 'cerulean'
      game 'gta5'
      author 'FHP'
      description 'FHP Callouts Configuration'
      version '1.0.0'

  # Final message
  - action: done
    message: |
      FHP vMenu Server deployed successfully!
      1. Add your FHP vehicle models to resources/[fhp]/fhp_vehicles
      2. Configure Discord IDs in permissions.cfg
      3. Start your server and enjoy!
